### ISSUE TITLE
Imoen in party disappears

### ISSUE THREAD

**Issue by Darpaek** [Gibberlings3/Imoen4Ever#11]
I have Imoen in my party.  We are still in Chapter 2.  Sometimes she just vanishes out of the party.  She doesn't leave.  She just disappears.  I try to CreateCreature("Imoen1") and it appears and she vanishes as soon as unpaused.

This usually seems to happen after resting with Romantic Encounters.  I've had this issue happen after RE with both Busya and Aimi after saving Trademeet.

A workaround is that I kick her out of the party, rest with the RE, and then go pick her up again at the Copper Coronet.  She doesn't disappear at CC.  Confirmed with both Busya and Aimi.

It may also have something to do with Chloe, who is in the party and romancing Imoen?

**Comment by Gitjas** [comment]
Kudos for finding a workaround. I'll note this down and keep it in mind. I am sure it's a mod conflict of sorts as I4E adds no script for Imoen to just disappear like that.
I don't know Chloe mod at all. Are you using Roxanne's version (e.g. via the EE Setup Tool that DLs her mod versions)?

**Comment by Darpaek** [comment]
Imoen is worth it.

 

Yes.  Roxanne’s Chloe with EET.

**Comment by Gitjas** [comment]
I don't have any knowledge about that Chloe version, sorry.
The EE Setup Tool downloads other than the original current mod versions so I don't think there is much I can do on my end to identify the incompatibility.  Thanks for reporting nontheless.

**Comment by Gitjas** [comment]
Closing this.
