### ISSUE TITLE
Installer does not function correctly.

### ISSUE THREAD

**Issue by sarkarinn** [Gibberlings3/Imoen4Ever#26]
Extracted the mod into EET BG2 and ran the EXE. I've concluded it does not function correctly. The installation menu asks if you want to install it all or ask about each one. If you pick the 'select each one' it auto skips everything, then only asks you about a portrait then says it's finished.

**Comment by Gitjas** [comment]
It sounds like it doesn't detect a valid game for the other components. The mod only works for BGII, BGII:EE, BG:SoD, EET, and BGT. Which game are you on? Can you post the content of the DEBUG file here?

**Comment by sarkarinn** [comment]
"EDIT 2; just in case: the mod needs to be installed before EET_End. it will skip if EET_End is detected." 

This was the problem. I was trying to add it to an existing EET install. I cannot add this mod to the install process on the mod manager as BWS/EET installer has no option to do so. 

https://github.com/Gibberlings3/EET - the installer I'm using. The infinity installer is terrible and does not work properly so I don't feel I have any options but to not use the mod at this point.

**Comment by Gitjas** [comment]
I guess you mean the EE Mod Setup Tool. You linked to the EET home which has nothing to do with the EE Setup Tool.
- I'll just hint that I do not recommend using the EE Setup Tool, one reason being that the changes made to the mods it loads mean that you will be on your own if you encounter bugs in your install. (One other is that, like you noticed, the maintainer excludes mods, for whatever reason.)

To your problem: You could deinstall EET_End by hand - if it's your last mod - install the SoD components of Imoen4Ever, and reinstall EET_End.
If there is more mods after EET_End then I wouldn't change the install order, unless you want to go through the hassle of uninstalling everything backwards, and afterwards reinstall everything again. I think it should work if the SoD-components of I4E are installed pretty late, though, so at least you wouldn't need to deinstall everything until the NPC mod section, but can install it later for this run.
Good luck!
